/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/zard.gltf')
    return (
        <group ref={group} {...props} dispose={null}>
            <group scale={[0.03, 0.03, 0.03]}>
                <primitive object={nodes.pm0006_00} />
                <skinnedMesh
                    geometry={nodes.Charizard_1.geometry}
                    material={materials.Material__12}
                    skeleton={nodes.Charizard_1.skeleton}
                />
                <skinnedMesh
                    geometry={nodes.Charizard_2.geometry}
                    material={materials.Material__13}
                    skeleton={nodes.Charizard_2.skeleton}
                />
                <skinnedMesh
                    geometry={nodes.Charizard_3.geometry}
                    material={materials.Material__14}
                    skeleton={nodes.Charizard_3.skeleton}
                />
                <skinnedMesh
                    geometry={nodes.Charizard_4.geometry}
                    material={materials.Material__15}
                    skeleton={nodes.Charizard_4.skeleton}
                />
                <skinnedMesh
                    geometry={nodes.Charizard_5.geometry}
                    material={materials.Material__16}
                    skeleton={nodes.Charizard_5.skeleton}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/zard.gltf')